import Head from "next/head";
import {
  Container,
  Main,
  Title,
  SummaryGrid,
} from "../components/sharedstyles";
import Cards from "../components/cards";
import { absoluteUrl, getLastDaysData } from "../lib/helper";
import { useRouter } from "next/router";
import SignUpTable from "../components/SignUpTable";
import { HandleOnClick, Login, Signup, Upgrade } from "../types";

export const getServerSideProps = (async () => {

  let overviewLoginsData: number = 0
  let overviewUpgradesData: number = 0
  let overviewSignupsData: Signup[] = []

  try {
    const loginResp = await fetch(absoluteUrl(`/api/logins`))
    const loginData = await loginResp.json()
    overviewLoginsData = getLastDaysData(loginData, 'date').length;
  } catch (error) {
    console.error(error);
  }

  try {
    const signupResp = await fetch(absoluteUrl(`/api/signups`))
    const signupData = await signupResp.json()
    overviewSignupsData = getLastDaysData(signupData, 'signupDate');
  } catch (error) {
    console.error(error);
  }

  try {
    const upgradesResp = await fetch(absoluteUrl(`/api/upgrades`))
    const upgradesData = await upgradesResp.json()
    overviewUpgradesData = getLastDaysData(upgradesData, 'upgradeDate').length;
  } catch (error) {
    console.error(error);
  }

  return {
    props: {
      loginsOverview: overviewLoginsData,
      signupsOverview: overviewSignupsData,
      upgradesOverview: overviewUpgradesData,
    },
  };
})

const Home = ({ loginsOverview, signupsOverview, upgradesOverview }) => {

  const router = useRouter();

  const handleOnClick: HandleOnClick = (userId: number) => {
    router.push(`/users/${userId}`)
  }

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
          <Title>Overview</Title>
          <SummaryGrid>
            <Cards title="New Signups" bottomText="since last 7 days" value={signupsOverview.length}  />
            <Cards title="New Logins" bottomText="since last 7 days" value={loginsOverview}  />
            <Cards title="New Upgrades" bottomText="since last 7 days" value={upgradesOverview}  />
          </SummaryGrid>
          <SignUpTable signups={signupsOverview} handleOnClick={handleOnClick}  />
        </Main>
    </Container>
  );
}

export default Home;